### ISSUE TITLE
u = pca.explained_variance_ratio_    is error 

### ISSUE THREAD

**Issue by everwind** [peter3125/sentence2vec#1]
it should be u=pca.components_[0],  the  pca.explained_variance_ratio_   is not the PCA vector  
pca.explained_variance_ratio_  #返回各个成分各自的方差百分比（贡献率） i

**Comment by everwind** [comment]
u = pca.explained_variance_ratio_  # the PCA vector
i think this code is error

**Comment by rock3125** [comment]
thanks everwind!  bug fixed.
