### ISSUE TITLE
How to generate vector for sentences

### ISSUE THREAD

**Issue by jx00109** [peter3125/sentence2vec#2]
I want to generate sentence embedding , for example, from dataset STS2012.MSRvid.txt
should I feed 1 sentence pair each time and generate sentence embeddings
OR
I need to feed all the sentences in STS2012.MSRvid.txt to generate sentence embeddings?

**Comment by rock3125** [comment]
We use PCA (principle component analysis) to finalize the semantic-composition of sentences.  To keep a long story short, it is probably best if you could pass all the sentences of an entire document / file as a single set for the sentence list for accuracy.  However, you could optimize this and pick a set of sentences (say a 100 or a 1000) and use these each time with a target sentence to provide a "frame of reference" for the PCA.
