### ISSUE TITLE
Value Error while trying to test with higher dimension vectors.

### ISSUE THREAD

**Issue by poornagurram** [peter3125/sentence2vec#3]
while loading vectors with high embedding size facing an issue while calculating the SIF

tried with google_news_vectors and glove 100 dimension and 25 dimension same error

error:
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by rock3125** [comment]
updated example to use 9x Google 300 vectors - please look at code and re-test your own code.  Seems to work fine.
