### ISSUE TITLE
The test data problem

### ISSUE THREAD

**Issue by yuquanle** [peter3125/sentence2vec#4]
Hi 
    I have seen your paper. In you experiment，the test data you have select I have some question. The 
STS’13 data I get in http://ixa2.si.ehu.es/sts/index.php%3Foption=com_content&view=article&id=49&Itemid=56.html. But I can't find the  STS.input.SMT.txt file. In STS’15 data，I find STS.gs.answers-forums.txt file have many blank score like this：
3.00

0.60

1.00

I hope you can provide me some help.
                                                                                                                                          best wish
                                                                                                                                        yuquanle

**Comment by rock3125** [comment]
Hi yuquanle,

I'm honoured to that you think I wrote that paper - alas- I am not the author.  I just took the algorithm described in the paper and implemented it in Python.  I haven't tested their data.  Please contact the authors of the paper if you want advice on how to use their data.

thanks!

Peter
