### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by divyansha** [peter3125/sentence2vec#5]
The line `vs = np.zeros(embedding_size)` seems incorrect to me, because `vs = np.add(vs, np.multiply(a_value, word.vector))` will not work if embedding_size < word.vector.shape[0].

Please let me know if my reasoning is correct. If so, I can push the correct changes, which would be `vs = np.zeros(sentence.word_list[0].vector.shape[0])`

**Comment by rock3125** [comment]
Thanks divyansha, you are correct.  And yes, the program will be incorrect when that happens.  However, the embedding size MUST NOT change to what the user specifies as it determines the size of the vectors.  Perhaps a check that this doesn't occur / raise ValueError() would be more appropriate?  I'd be happy if you wanted to make that change to approve it.

**Comment by divyansha** [comment]
Done. I've tested the code before pushing. None of those issues occur, and the embedding size does not change

**Comment by AnLiGentile** [comment]
the line vs = np.zeros(sentence.word_list[0].vector.shape[0]) generates the following error:
    
vs = np.zeros(sentence.word_list[0].vector.shape[0])  # add all word2vec values into one vector for the sentence
AttributeError: 'list' object has no attribute 'shape'

**Comment by divyansha** [comment]
sentence.word_list[0].vector is a numpy array for me. Not sure why we're getting different types for sentence.word_list[0].vector

**Comment by rock3125** [comment]
I'll roll the PR back for now.

**Comment by rock3125** [comment]
OK - shape[] only applies to numpy vectors - the example uses a plain Python vector that doesn't support shape().  The error checking isn't that important and should really be taken care of by whatever uses the sentence2vec function.  This is just a small example and an implementation of the algorithm.
