### ISSUE TITLE
is there something wrong with u*u.T? I think this should be a matrix while your is a vector?

### ISSUE THREAD

**Issue by fydlzr** [peter3125/sentence2vec#7]
I'm confused.
I think u * u.T should be either a float or a (n * n) matrix.
Not a n * 1 vector.
Please correct me if I am wrong.
Thanks.

**Comment by rock3125** [comment]
you're nearly there - when you multiply u by its transpose (u * u.T) you get basically a square matrix as the result - so in effect - (u * u.T) turns a 1 dimensional vector of size n into a 2 dimensional matrix of n x n.

**Comment by fydlzr** [comment]
when I run your code and print out the shape of u and u * u.T,
I got both (300,), not a (300, 300).
Maybe u should be reshape to (300,1) first?

**Comment by rock3125** [comment]
you are right -it just squares the values - this is done to get the "a squared dropoff" I think - and then THIS value is used a few lines down to subtract and adjust the sentence embeddings accordingly.  I can't pretend to understand it exactly, but there is a paper of the same name that explains the math if you like.
