### ISSUE TITLE
Use of PCA

### ISSUE THREAD

**Issue by christophsk** [peter3125/sentence2vec#8]
If I'm not mistaken, PCA centers the data on the mean. In the referenced article (page 4, footnote 3) the authors state that the principal component is computed without centralizing. TruncatedSVD should probably be used instead of PCA.

Also, their algorithm says nothing about padding. Can you explain the rationale behind this?

**Comment by rock3125** [comment]
the padding is used to set the correct size for the coming matrix multiplication afterwards (as you can only multiply M(i,j) with N(j,i) where i and j are the sizes of Matrices M and N).  The authors suggested using either PCA or SVD (page 1 abstract) - you're probably right about it being slightly more accurate with SVD though.
